import type { RenderContext } from '../types.js';

export interface BodySections {
  /** Second person, one or two sentences. */
  role: string;
  /** Ordered steps the agent follows. */
  method: string[];
  /** How the agent proves it is done. Omit only if genuinely unverifiable. */
  verification?: string;
  /** What the agent must not do. Scoping beats politeness here. */
  boundaries: string[];
}

/**
 * Assembles an agent system prompt. Every generated body ends with a rules
 * reference rather than a copy of the repo's conventions: a restated rule
 * diverges from its source the first time either is edited, and the stale copy
 * is the one the agent will obey.
 */
export function buildBody(ctx: RenderContext, sections: BodySections): string {
  const parts: string[] = [sections.role.trim(), ''];

  parts.push('## Method', '');
  sections.method.forEach((step, i) => parts.push(`${i + 1}. ${step}`));
  parts.push('');

  if (sections.verification) {
    parts.push('## Verification', '', sections.verification, '');
  }

  parts.push('## Boundaries', '');
  for (const boundary of sections.boundaries) parts.push(`- ${boundary}`);
  parts.push('');

  const ruleFiles = ctx.all
    .filter((e) => e.kind === 'stated-rules')
    .map((e) => e.data?.['file'] as string)
    .filter(Boolean);

  if (ruleFiles.length > 0) {
    parts.push(
      '## Repository conventions',
      '',
      `This repository states its conventions in ${andList(ruleFiles)}. Read the relevant file and follow it.`,
      'Do not restate those rules here or re-derive them from the code — reference them, so there is one copy to keep current.',
      '',
    );
  }

  parts.push(
    '## Provenance',
    '',
    'You were generated by `agentrouter` from evidence in this repository:',
    '',
  );
  for (const support of ctx.support) {
    parts.push(`- **${support.mechanism}** — ${support.rationale}`);
    for (const e of support.evidence.slice(0, 3)) {
      parts.push(`  - ${e.value} \`(${e.source})\``);
    }
  }

  return parts.join('\n').trimEnd();
}

function andList(items: string[]): string {
  const unique = [...new Set(items)];
  if (unique.length === 1) return `\`${unique[0]}\``;
  const last = unique.pop() as string;
  return `${unique.map((i) => `\`${i}\``).join(', ')} and \`${last}\``;
}
