import type { Roster } from '../types.js';
import type { Emitter, PlannedWrite } from './types.js';

const FILE = 'AGENTS.md';
const START = '<!-- agentrouter:begin -->';
const END = '<!-- agentrouter:end -->';

/**
 * Writes a managed block into `AGENTS.md`, the one agent-adjacent convention
 * that more than one tool reads.
 *
 * This emitter is deliberately modest. `AGENTS.md` is a document of record, not
 * an executable agent format, so what belongs here is the roster and its
 * reasoning — enough that a reader who has never run agentrouter understands what
 * the agents are and why they exist. Anything outside the managed block is left
 * exactly as the repository wrote it.
 */
export const agentsMdEmitter: Emitter = {
  name: 'agents-md',
  plan(roster: Roster, read: (rel: string) => string | null): PlannedWrite[] {
    const block = [START, '', ...renderBlock(roster), '', END].join('\n');
    const existing = read(FILE);
    const contents = existing === null ? `# Agents\n\n${block}\n` : replaceBlock(existing, block);
    return [
      {
        path: FILE,
        contents,
        action: existing === null ? 'create' : existing === contents ? 'unchanged' : 'update',
      },
    ];
  },
};

function renderBlock(roster: Roster): string[] {
  const lines: string[] = [
    '## Agent roster',
    '',
    `Generated by agentrouter from repository evidence. Specs live in \`.agentrouter/roster.json\`;`,
    'edit those rather than the rendered agent files.',
    '',
  ];

  if (roster.agents.length === 0) {
    lines.push('_No agent in the catalog was justified by this repository\'s evidence._', '');
  }

  for (const agent of roster.agents) {
    lines.push(
      `### \`${agent.name}\``,
      '',
      agent.description,
      '',
      `- **Justified by:** ${agent.mechanisms.join(', ')}`,
      `- **Tools:** ${agent.tools.join(', ')}`,
      `- **Considered instead:** ${agent.rejectedAlternative}`,
      '',
    );
  }

  if (roster.rejections.length > 0) {
    lines.push(
      '## Considered and rejected',
      '',
      'These were evaluated and did not qualify as agents here. They are listed so the',
      'absence is a decision on the record rather than an oversight.',
      '',
    );
    for (const rejection of roster.rejections) {
      lines.push(`- **${rejection.title}** — ${rejection.verdict} ${rejection.detail}`);
    }
    lines.push('');
  }
  return lines;
}

function replaceBlock(existing: string, block: string): string {
  const start = existing.indexOf(START);
  const end = existing.indexOf(END);
  if (start === -1 || end === -1 || end < start) {
    return `${existing.trimEnd()}\n\n${block}\n`;
  }
  return `${existing.slice(0, start)}${block}${existing.slice(end + END.length)}`;
}
